### ISSUE TITLE
Could not make it work..

### ISSUE THREAD

**Issue by arasic** [bonsaiviking/p0fclient#1]
Just wanted to say first that this idea is really great because it allows me to introduce p0f in any python project. 
Maybe I was doing something incorrectly..
I launched : 
**p0f as sudo ./p0f -i br0 -s "/var/run/p0f.sock" -d -u alis -o /var/log/p0f.log**
where ls -la "/var/run/p0f.sock" : 
srw-rw-rw- 1 root root 0 Nov 20 22:57 /var/run/p0f.sock

Then, installed p0f-client and launched it as : 
 **p0f-client /var/run/p0f.sock 192.168.2.4**
/var/run/p0f.sock
Traceback (most recent call last):
  File "/usr/local/bin/p0f-client", line 16, in <module>
    info = p0f.query(addr)
  File "/usr/local/lib/python2.7/dist-packages/p0fclient/p0fclient.py", line 77, in query
    a = ipaddr.IPAddress(ip)
  File "/usr/local/lib/python2.7/dist-packages/ipaddr.py", line 78, in IPAddress
    address)
ValueError: '/var/run/p0f.sock' does not appear to be an IPv4 or IPv6 address

but if i try without specifying "/var/run/p0f.sock" as  : 
**p0f-client 192.168.2.4**

/var/run/p0f.sock
Traceback (most recent call last):
  File "/usr/local/bin/p0f-client", line 16, in <module>
    info = p0f.query(addr)
  File "/usr/local/lib/python2.7/dist-packages/p0fclient/p0fclient.py", line 83, in query
    return self.parse_response( self.sock.recv(232) )
  File "/usr/local/lib/python2.7/dist-packages/p0fclient/p0fclient.py", line 48, in parse_response
    raise CommError, "Bad query"
p0fclient.p0fclient.CommError: Bad query

netstat returns : 
sudo netstat -lapn | grep p0f
unix  2      [ ACC ]     STREAM     LISTENING     702256798 5027/p0f            /var/run/p0f.sock

**Comment by alopyrev** [comment]
I'm having the same error, did you end up resolving it?

**Comment by alopyrev** [comment]
i mean it weirdly did work until reboot, after the reboot I started getting the same error as mentioned above and then when i tried fresh install on a fresh vm i got the exact error straight away

**Comment by alopyrev** [comment]
@arasic did you end up finding a solution?

**Comment by arasic** [comment]
Sorry for a late response alopyrev. No, I did not manage to make it work
either.

On Oct 21, 2017 3:40 PM, "alopyrev" <notifications@github.com> wrote:

@arasic <https://github.com/arasic> did you end up finding a solution?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/bonsaiviking/p0fclient/issues/1#issuecomment-338427410>,
or mute the thread
